"""add import counts and import_errors

Revision ID: 2db755e1146b
Revises: d6043a70b7c2
Create Date: 2026-09-05 23:38:14.297456

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2db755e1146b'
down_revision: Union[str, Sequence[str], None] = 'd6043a70b7c2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('import_errors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('import_id', sa.String(length=32), nullable=False),
    sa.Column('scope', sa.String(length=16), nullable=False),
    sa.Column('row_number', sa.Integer(), nullable=True),
    sa.Column('invoice_number', sa.String(length=100), nullable=True),
    sa.Column('vendor', sa.String(length=255), nullable=True),
    sa.Column('code', sa.String(length=48), nullable=False),
    sa.Column('field', sa.String(length=64), nullable=True),
    sa.Column('message', sa.String(length=500), nullable=False),
    sa.ForeignKeyConstraint(['import_id'], ['import_jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_import_errors_import_id'), 'import_errors', ['import_id'], unique=False)
    op.add_column('import_jobs', sa.Column('total_rows', sa.Integer(), server_default='0', nullable=False))
    op.add_column('import_jobs', sa.Column('valid_rows', sa.Integer(), server_default='0', nullable=False))
    op.add_column('import_jobs', sa.Column('invalid_rows', sa.Integer(), server_default='0', nullable=False))
    op.add_column('import_jobs', sa.Column('invoices_found', sa.Integer(), server_default='0', nullable=False))
    op.add_column('import_jobs', sa.Column('invoices_created', sa.Integer(), server_default='0', nullable=False))
    op.add_column('import_jobs', sa.Column('invoices_failed', sa.Integer(), server_default='0', nullable=False))
    op.add_column('import_jobs', sa.Column('duplicate_invoices', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('import_jobs', 'duplicate_invoices')
    op.drop_column('import_jobs', 'invoices_failed')
    op.drop_column('import_jobs', 'invoices_created')
    op.drop_column('import_jobs', 'invoices_found')
    op.drop_column('import_jobs', 'invalid_rows')
    op.drop_column('import_jobs', 'valid_rows')
    op.drop_column('import_jobs', 'total_rows')
    op.drop_index(op.f('ix_import_errors_import_id'), table_name='import_errors')
    op.drop_table('import_errors')
    # ### end Alembic commands ###
