"""add updated_at to invoices

Revision ID: e4fd0b79bf05
Revises: 1187a8364717
Create Date: 2026-09-04 21:28:41.353934

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e4fd0b79bf05'
down_revision: Union[str, Sequence[str], None] = '1187a8364717'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Add updated_at, in three steps rather than one.

    Autogenerate produced a single statement:

        op.add_column('invoices',
            sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False))

    which fails on any table that already has rows:

        psycopg.errors.NotNullViolation: column "updated_at" of relation
        "invoices" contains null values

    Autogenerate compares two schemas. It has no idea whether the table holds
    zero rows or ten million, so it cannot know a backfill is required. Adding
    a NOT NULL column to a populated table always takes these three steps:
    """
    # 1. add it nullable, so existing rows are allowed to have no value yet
    op.add_column(
        "invoices",
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
    )

    # 2. backfill. An invoice that has never been modified was last "updated"
    #    when it was created, so created_at is the honest value.
    op.execute("UPDATE invoices SET updated_at = created_at")

    # 3. now that every row has a value, the constraint can be enforced
    op.alter_column("invoices", "updated_at", nullable=False)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('invoices', 'updated_at')
    # ### end Alembic commands ###
